### ISSUE TITLE
PF2e System compatibility

### ISSUE THREAD

**Issue by Aulcus** [etiquettestartshere/chatedit#8]
Opening the context menu in a pf2e (6.3.1) world on v12 (12.331) doesn't show any of the options to edit the message or change it to IC/OoC. Tested it in a fresh world with no modules turned on except for this one.

It might be due to the way messages are coded in the pf2e system, so unfortunately the module doesn't seem to function at all, except for the settings menu showing up.

The following error pops up in the console when right clicking a message:
![FVTT_Chat_Edit_Console_Warning](https://github.com/user-attachments/assets/6d7a3948-9b23-4f9e-85aa-ca956f7677a8)

**Comment by etiquettestartshere** [comment]
the reason is because pf2e allows every message to be popped out, and this module filters for that. i will reconsider this approach, or simply allow more messsages to be edited even though it may cause problems 🤣
